### ISSUE TITLE
Fisk error when running the test suite, on a Clang-compiled Ruby

### ISSUE THREAD

**Issue by 64kramsystem** [tenderlove/tenderjit#35]
I've compiled Ruby with Clang, in order to investigate the two todos in `ruby_internals.rb`, however, I experience unexpected failures in the test suite.

Specifically, I get 16 failures like the following:

```
  1) Error:
TenderJIT::MethodRecursion#test_fib:
NotImplementedError: Couldn't find instruction CMP imm32, m64
Valid forms:
    CMP al, imm8
    CMP r8, imm8
    CMP r8, r8
    CMP r8, m8
    CMP ax, imm16
    CMP r16, imm8
    CMP r16, imm16
    CMP r16, r16
    CMP r16, m16
    CMP eax, imm32
    CMP r32, imm8
    CMP r32, imm32
    CMP r32, r32
    CMP r32, m32
    CMP rax, imm32
    CMP r64, imm8
    CMP r64, imm32
    CMP r64, r64
    CMP r64, m64
    CMP m8, imm8
    CMP m8, r8
    CMP m16, imm8
    CMP m16, imm16
    CMP m16, r16
    CMP m32, imm8
    CMP m32, imm32
    CMP m32, r32
    CMP m64, imm8
    CMP m64, imm32
    CMP m64, r64

    /path/to/fisk-e3d21ac5df10/lib/fisk.rb:829:in `gen_with_insn'
    /path/to/fisk-e3d21ac5df10/lib/fisk/instructions.rb:1643:in `cmp'
    /path/to/tenderjit-dev/lib/tenderjit/runtime.rb:270:in `block (2 levels) in if_eq'
    /path/to/tenderjit-dev/lib/tenderjit/runtime.rb:423:in `maybe_reg'
    /path/to/tenderjit-dev/lib/tenderjit/runtime.rb:269:in `block in if_eq'
    /path/to/tenderjit-dev/lib/tenderjit/runtime.rb:423:in `maybe_reg'
    /path/to/tenderjit-dev/lib/tenderjit/runtime.rb:268:in `if_eq'
    /path/to/tenderjit-dev/lib/tenderjit/iseq_compiler.rb:1085:in `block (2 levels) in compile_opt_send_without_block'
    /path/to/tenderjit-dev/lib/tenderjit/runtime.rb:284:in `else'
    /path/to/tenderjit-dev/lib/tenderjit/iseq_compiler.rb:1078:in `block in compile_opt_send_without_block'
    /path/to/tenderjit-dev/lib/tenderjit/iseq_compiler.rb:1831:in `with_runtime'
    /path/to/tenderjit-dev/lib/tenderjit/iseq_compiler.rb:1041:in `compile_opt_send_without_block'
    /path/to/tenderjit-dev/test/tenderjit_test.rb:33:in `fib'
    /path/to/tenderjit-dev/test/tenderjit_test.rb:47:in `test_fib'
```

Ruby configuration:

```
$ ruby -rrbconfig -e'puts File.join RbConfig::CONFIG["prefix"], "lib", RbConfig::CONFIG["LIBRUBY"]'
/path/to/lib/libruby.so.3.0.2

$ ruby -rrbconfig -e'p RbConfig::CONFIG["CFLAGS"]'
"-O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens  -fPIC"

$ ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]'
"clang -fdeclspec"
```

**Comment by tenderlove** [comment]
Huh, interesting.  That error means that Fisk can't find a `CMP` instruction that takes `imm32` and `m64` operands.  For context, I'm looking at [this line](https://github.com/tenderlove/tenderjit/blob/f3794e91d9cbd58bb2f1e36905db8c496b8c2127/lib/tenderjit/iseq_compiler.rb#L1085) from your stack trace.

We're caching the object class that was seen at compile time in the generated machine code.  Whatever class pointer was stored on `recv` at that time gets cached as an immediate value in machine code.  Fisk tries to fit immediate values in the smallest possible width.  In this case it looks like it was able to fit the address of the class in a 32 bit immediate.  The problem though is that there is no `CMP` instruction that has a 32 bit immediate on the left hand side.

I *think* if we just swap the operands on that line, it should "just work".  IOW change:

```
rt.if_eq(RBasic.klass(recv), recv_ptr.basic.klass).
```

to:

```
rt.if_eq(recv_ptr.basic.klass, RBasic.klass(recv)).
```

This is pretty surprising since I thought we had test coverage for this line.  I wonder why it's failing now 😳

**Comment by 64kramsystem** [comment]
Thanks :star_struck: 

This works, however, I'm going to take some time to dig a little bit further (in things I don't understand :joy:).

Right now, the thing that popped to my eyes after a brief debugging sessions is that here:

```rb
[263, 272] in lib/tenderjit/runtime.rb
   263: 
   264:     def if_eq lhs, rhs
   265:       lhs = cast_to_fisk lhs
```

In the Clang-compiled version, `lhs` is a `Fisk::Imm32`, while in the GCC one, it's a `Fisk::Imm64` :thinking:.

**Comment by tenderlove** [comment]
That's really weird.  The error message from Fisk is printing out the different forms of the `CMP` instruction that *are* available.  None of the available forms have an immediate on the LHS (32 bit *or* 64 bit).  I would expect an error with GCC or Clang.

Ah, this is very silly.  As I was typing this out, I looked at the source.  `maybe_reg` will put the immediate in to a register [but only if it's a 64 bit immediate](https://github.com/tenderlove/tenderjit/blob/f3794e91d9cbd58bb2f1e36905db8c496b8c2127/lib/tenderjit/runtime.rb#L416-L422).

We should make `if_eq` a little smarter.  Since we know `if_eq` will use the `CMP` instruction, we should only move the lhs in to a register if it's an immediate.  If the rhs is an immediate we should just leave it as-is.

Also we might want to issue a warning or swap params if the lhs is an immediate and the rhs is *not* an immediate.  The code in `main` is emitting an extra `mov` instruction because the lhs is an immediate when we could have put the lhs in the rhs and directly used the `CMP` instruction.

**Comment by 64kramsystem** [comment]
Phew :sweat_smile: Thanks for the explanations :star_struck:. I'll give this a go over the next couple of days :+1:
